let componentData_ = [
  [],
  [{
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "style",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "&nbsp;",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 1341,
      "height": 70,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "rgba(249, 255, 228, 1)",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": -1,
      "left": 2
    },
    "id": "oomRgNA0-ghX8fJBNHm-t"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "style",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "&nbsp;",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 1342,
      "height": 687,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "rgba(251, 252, 179, 1)",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 69,
      "left": 1.5
    },
    "id": "w78c_cjiZRvJY7x-ljWjE"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "CircleShape",
    "label": "圆形",
    "propValue": "&nbsp;",
    "icon": "24gl-circle",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 646,
      "height": 35,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 8,
      "left": 349.5
    },
    "id": "U-4pjvbEl4bD5ieBWyUjg"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "搜索",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 60,
      "height": 26,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 13,
      "left": 839
    },
    "id": "R2S4Ep9FQGMKkDVFi4rD0"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "衬衫 男 长袖",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 13,
      "left": 413
    },
    "id": "qTNPOsvUtuwekLoImebbK"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "&nbsp;",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 396,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 112,
      "left": 94
    },
    "id": "nDsqmKeRE26sHTEmDMERk"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "居家生活",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 112,
      "left": 94
    },
    "id": "fbM9t6_j9-mWbaOlVqC5U"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "女装/女鞋/女士精品",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 140,
      "left": 94
    },
    "id": "sbhSLIgeSMXAjMB4o9sha"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "运动户外",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 224,
      "left": 94
    },
    "id": "qXl-CpDuH86r9gFNqBngr"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "箱包/配饰",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 196,
      "left": 94
    },
    "id": "BiHCn2fRH82B3pcypnR1g"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "男装/男鞋/男士精品",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 168,
      "left": 94
    },
    "id": "PP5htMxKZ_yfVCf2xaxHh"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "3C数码/手机/智能设备",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 252,
      "left": 94
    },
    "id": "WU34hh86EC_qSEVecO9Tl"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "模玩/动漫/周边",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 308,
      "left": 94
    },
    "id": "8JgkZFrl1n3dbjEioN_M5"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "笔记本/网络服务",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 280,
      "left": 94
    },
    "id": "CfEGMw2PuDy3SPBXj-biS"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "玩具/母婴产品",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 336,
      "left": 94
    },
    "id": "S2Ms7dMgigIvyOtNtapSH"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "家电/影音",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 392,
      "left": 94
    },
    "id": "oT5DdBOINyWAlESBWBvQc"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "汽车/虚拟",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 364,
      "left": 94
    },
    "id": "DWuNpGZd1Kw-BnHTNvk7Q"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "美妆/洗护",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 420,
      "left": 94
    },
    "id": "UKIej3FQHk9XBfJq_Q_9t"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "医疗健康",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 476,
      "left": 94
    },
    "id": "DbsPXvAKJUNkwa4hFb_wS"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "零食饮料",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 448,
      "left": 94
    },
    "id": "yNS2DAR1F04bs8FiNUu-1"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "轮播图",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 684,
      "height": 202,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 112,
      "left": 294
    },
    "id": "_m0zOBimClama0Ru9pPN2"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "图1",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 350,
      "height": 192,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 314,
      "left": 294
    },
    "id": "EHXoOq3QlnBlttfCKFYD3"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "图2",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 334,
      "height": 192,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 314,
      "left": 644
    },
    "id": "9jvbmHefVWEE8HtU-0T32"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "&nbsp;",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 252,
      "height": 394,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 112,
      "left": 979
    },
    "id": "3TxKejyXOuWFdm_OmiOHK"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VButton",
    "label": "按钮",
    "propValue": "登录",
    "icon": "button",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 100,
      "height": 34,
      "borderWidth": 1,
      "borderColor": "",
      "borderRadius": "",
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "backgroundColor": "",
      "top": 204,
      "left": 995.5
    },
    "id": "fQ-VHj0a9bzfxNO1eE6sv"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VButton",
    "label": "按钮",
    "propValue": "注册领红包",
    "icon": "button",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 100,
      "height": 34,
      "borderWidth": 1,
      "borderColor": "",
      "borderRadius": "",
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "backgroundColor": "",
      "top": 204,
      "left": 1116
    },
    "id": "faDFJK5fQ5aL3bHUPPNrc"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "CircleShape",
    "label": "圆形",
    "propValue": "头像",
    "icon": "24gl-circle",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 59,
      "height": 52,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 136,
      "left": 1073.5
    },
    "id": "6ixZrGPRSDe_0uUwEeXh4"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "官方物流寄送至全球十地",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 250,
      "height": 49,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 265,
      "left": 979
    },
    "id": "pblxl8gD2_AxR7Y56VK5F"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "支持国际信用卡支付",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 252,
      "height": 49,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 314,
      "left": 977
    },
    "id": "5MW5sB-7c8Wjj2_dVEcAl"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "常用功能介绍&购物指南",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 251,
      "height": 49,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 363,
      "left": 979
    },
    "id": "B4D0O90GW6CkkcpZ7vrYh"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "买家保障&购物无忧",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 250,
      "height": 49,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 412,
      "left": 980
    },
    "id": "r852rMYrwjQdUiuS47ynD"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "&nbsp;",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 1135,
      "height": 178,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 549,
      "left": 92
    },
    "id": "Hsckjzs_hnOKKirTWRvlJ"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "&nbsp;",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 373,
      "height": 177,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 550,
      "left": 92
    },
    "id": "fYkuYaWS72Rww9WuSxa9u"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "&nbsp;",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 388,
      "height": 177,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 550,
      "left": 466
    },
    "id": "2O73IwTtjoqFycS2HbeAS"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "&nbsp;",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 371,
      "height": 177,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 550,
      "left": 855
    },
    "id": "H6X_5NxXSeMWh0CzEwmnI"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "iFashion",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 550,
      "left": 94
    },
    "id": "XyDXeSC6wp0XIr6OPtXIe"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "海外天天特卖",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 550,
      "left": 466
    },
    "id": "IpOtcfcbSEmdf6i9Mom4I"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "淘宝直播",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 200,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 550,
      "left": 855
    },
    "id": "A0NrCAibAwOKg6LnRQa1e"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "图",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 279,
      "height": 107,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 594,
      "left": 139
    },
    "id": "Gml0QL1FlUEA8pw-6FlvY"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "图",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 279,
      "height": 107,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 594,
      "left": 520.5
    },
    "id": "nw79Vv4MKZ_iVZhXFLInc"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "图",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 279,
      "height": 107,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 594,
      "left": 906
    },
    "id": "U84-pGMyU8LX-0WDqOaUi"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "VText",
    "label": "文字",
    "propValue": "手表 拖鞋男 男士风衣 宝马山地自行车 男包 洗衣机 水杯 休闲皮鞋 冬装男 更多",
    "icon": "wenben",
    "request": {
      "method": "GET",
      "data": [],
      "url": "",
      "series": false,
      "time": 1000,
      "paramType": "",
      "requestCount": 0
    },
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 707,
      "height": 28,
      "fontSize": "",
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "",
      "color": "",
      "top": 41,
      "left": 404
    },
    "id": "8Y_Xy-3_TFar3a6a4e-lo"
  }, {
    "animations": [],
    "events": {},
    "groupStyle": {},
    "isLock": false,
    "collapseName": "style",
    "linkage": {
      "duration": 0,
      "data": [{"id": "", "label": "", "event": "", "style": [{"key": "", "value": ""}]}]
    },
    "component": "RectShape",
    "label": "矩形",
    "propValue": "淘宝",
    "icon": "juxing",
    "style": {
      "rotate": 0,
      "opacity": 1,
      "width": 129,
      "height": 46,
      "fontSize": 25,
      "fontWeight": 400,
      "lineHeight": "",
      "letterSpacing": 0,
      "textAlign": "center",
      "color": "rgba(245, 157, 16, 1)",
      "borderColor": "#000",
      "borderWidth": 1,
      "backgroundColor": "",
      "borderStyle": "solid",
      "borderRadius": "",
      "verticalAlign": "middle",
      "top": 13,
      "left": 94
    },
    "id": "nx203vOPWdFDvSwKzDPpB"
  }],


]

let canvasStyleData_ = [
  {
    "width": 1920,
    "height": 1020,
    "scale": 100,
    "color": "#000",
    "opacity": 1,
    "background": "#fff",
    "fontSize": 14
  },
  {
    "width": "1920",
    "height": "1080",
    "scale": 70,
    "color": "#000",
    "opacity": 1,
    "background": "#fff",
    "fontSize": 14
  }
]

export {componentData_, canvasStyleData_};
